import { InstantiationService, ServiceCollection, SyncDescriptor } from './di';
import { ActivationService, IActivationService } from './services/activation';
import { AdapterRegistry, IAdapterRegistry } from './services/adapters';
import { AuthService, IAuthService } from './services/auth';
import { BackupService, IBackupService } from './services/backup';
import { CryptoService, ICryptoService } from './services/crypto';
import { DoctorService, IDoctorService } from './services/doctor';
import { DriftService, IDriftService } from './services/drift';
import { EnvironmentService, IEnvironmentService } from './services/environment';
import { FileService, IFileService } from './services/files';
import { ILiveWriteService, LiveWriteService } from './services/live-write';
import { ILogService, LogService } from './services/log';
import { IProfileService, ProfileService } from './services/profiles';
import { HarnessRegistry, IHarnessRegistry } from './services/registry';
import { ITransferService, TransferService } from './services/transfer';
import { IUserSyncService, UserSyncService } from './services/user-sync';
import { IUserService, UserService } from './services/users';
import { IVaultService, VaultService } from './services/vault';

export function createServices(): InstantiationService {
  const collection = new ServiceCollection();
  collection.set(ILogService, new SyncDescriptor(LogService));
  collection.set(IEnvironmentService, new SyncDescriptor(EnvironmentService));
  collection.set(IUserService, new SyncDescriptor(UserService));
  collection.set(IUserSyncService, new SyncDescriptor(UserSyncService));
  collection.set(IFileService, new SyncDescriptor(FileService));
  collection.set(ICryptoService, new SyncDescriptor(CryptoService));
  collection.set(IAuthService, new SyncDescriptor(AuthService));
  collection.set(IHarnessRegistry, new SyncDescriptor(HarnessRegistry));
  collection.set(IAdapterRegistry, new SyncDescriptor(AdapterRegistry));
  collection.set(IBackupService, new SyncDescriptor(BackupService));
  collection.set(ILiveWriteService, new SyncDescriptor(LiveWriteService));
  collection.set(IVaultService, new SyncDescriptor(VaultService));
  collection.set(IProfileService, new SyncDescriptor(ProfileService));
  collection.set(IActivationService, new SyncDescriptor(ActivationService));
  collection.set(ITransferService, new SyncDescriptor(TransferService));
  collection.set(IDriftService, new SyncDescriptor(DriftService));
  collection.set(IDoctorService, new SyncDescriptor(DoctorService));
  return new InstantiationService(collection);
}
