import { InstantiationService, ServiceCollection, SyncDescriptor } from './di';
import { ActivationService, IActivationService } from './services/activation';
import { AdapterRegistry, IAdapterRegistry } from './services/adapters';
import { AuthService, IAuthService } from './services/auth';
import { BackupService, IBackupService } from './services/backup';
import { CodexLoginCacheService, ICodexLoginCacheService } from './services/codex-login-cache';
import { CryptoService, ICryptoService } from './services/crypto';
import { DoctorService, IDoctorService } from './services/doctor';
import { DriftService, IDriftService } from './services/drift';
import { EnvironmentService, IEnvironmentService } from './services/environment';
import { FileService, IFileService } from './services/files';
import { GitHubSyncService, IGitHubSyncService } from './services/github-sync';
import { IJournalService, JournalService } from './services/journal';
import { ILiveWriteService, LiveWriteService } from './services/live-write';
import { ILogService, LogService } from './services/log';
import { IProbeService, ProbeService } from './services/probe';
import { IProbeCacheService, ProbeCacheService } from './services/probe-cache';
import { IProfileService, ProfileService } from './services/profiles';
import { HarnessRegistry, IHarnessRegistry } from './services/registry';
import { IScanService, ScanService } from './services/scan';
import { ITransferService, TransferService } from './services/transfer';
import { IUserAccessService, UserAccessService } from './services/user-access';
import { IUserSyncService, UserSyncService } from './services/user-sync';
import { IUserService, UserService } from './services/users';
import { IVaultService, VaultService } from './services/vault';

export function createServices(): InstantiationService {
  const collection = new ServiceCollection();
  collection.set(ILogService, new SyncDescriptor(LogService));
  collection.set(IEnvironmentService, new SyncDescriptor(EnvironmentService));
  collection.set(IUserService, new SyncDescriptor(UserService));
  collection.set(IUserAccessService, new SyncDescriptor(UserAccessService));
  collection.set(IUserSyncService, new SyncDescriptor(UserSyncService));
  collection.set(IFileService, new SyncDescriptor(FileService));
  collection.set(ICodexLoginCacheService, new SyncDescriptor(CodexLoginCacheService));
  collection.set(ICryptoService, new SyncDescriptor(CryptoService));
  collection.set(IAuthService, new SyncDescriptor(AuthService));
  collection.set(IHarnessRegistry, new SyncDescriptor(HarnessRegistry));
  collection.set(IAdapterRegistry, new SyncDescriptor(AdapterRegistry));
  collection.set(IBackupService, new SyncDescriptor(BackupService));
  collection.set(IJournalService, new SyncDescriptor(JournalService));
  collection.set(IScanService, new SyncDescriptor(ScanService));
  collection.set(ILiveWriteService, new SyncDescriptor(LiveWriteService));
  collection.set(IVaultService, new SyncDescriptor(VaultService));
  collection.set(IProfileService, new SyncDescriptor(ProfileService));
  collection.set(IProbeService, new SyncDescriptor(ProbeService));
  collection.set(IProbeCacheService, new SyncDescriptor(ProbeCacheService));
  collection.set(IActivationService, new SyncDescriptor(ActivationService));
  collection.set(ITransferService, new SyncDescriptor(TransferService));
  collection.set(IGitHubSyncService, new SyncDescriptor(GitHubSyncService));
  collection.set(IDriftService, new SyncDescriptor(DriftService));
  collection.set(IDoctorService, new SyncDescriptor(DoctorService));
  return new InstantiationService(collection);
}
