import { join } from 'node:path';
import type { ActivePublic, HarnessId } from '@seaveyon/harness-switch-shared';
import { createDecorator, inject } from '../di';
import { IEnvironmentService } from './environment';
import { IFileService } from './files';
import { IProfileService } from './profiles';
import { IHarnessRegistry } from './registry';

type ActiveStore = Record<
  string,
  {
    name: string;
    base_url: string;
    api_key: string;
    model: string;
  }
>;

const ENV_MAP: Record<HarnessId, Record<string, 'baseUrl' | 'apiKey' | 'model'>> = {
  claude: {
    ANTHROPIC_BASE_URL: 'baseUrl',
    ANTHROPIC_API_KEY: 'apiKey',
    ANTHROPIC_MODEL: 'model',
  },
  codex: {
    OPENAI_BASE_URL: 'baseUrl',
    OPENAI_API_KEY: 'apiKey',
    CODEX_MODEL: 'model',
  },
  pi: {
    PI_API_BASE: 'baseUrl',
    PI_API_KEY: 'apiKey',
    PI_MODEL: 'model',
  },
  zcode: {
    ZCODE_BASE_URL: 'baseUrl',
    ZCODE_API_KEY: 'apiKey',
    ZCODE_MODEL: 'model',
  },
  kimi: {
    KIMI_BASE_URL: 'baseUrl',
    KIMI_API_KEY: 'apiKey',
    KIMI_MODEL: 'model',
  },
};

export interface IActivationService {
  readonly _serviceBrand: undefined;
  getActive(harness: HarnessId): ActivePublic | null;
  activate(harness: HarnessId, name: string): string;
}

export const IActivationService = createDecorator<IActivationService>('activationService');

@inject(IEnvironmentService, IFileService, IHarnessRegistry, IProfileService)
export class ActivationService implements IActivationService {
  declare readonly _serviceBrand: undefined;

  constructor(
    private readonly environment: IEnvironmentService,
    private readonly files: IFileService,
    private readonly harnesses: IHarnessRegistry,
    private readonly profiles: IProfileService,
  ) {}

  getActive(harness: HarnessId): ActivePublic | null {
    const stored = this.read()[harness];
    if (!stored) {
      return null;
    }
    return {
      name: stored.name,
      baseUrl: stored.base_url || '',
      model: stored.model || '',
    };
  }

  activate(harness: HarnessId, name: string): string {
    const profile = this.profiles.decrypt(harness, name);
    const active = this.read();
    active[harness] = {
      name: profile.name,
      base_url: profile.baseUrl,
      api_key: profile.apiKey,
      model: profile.model,
    };
    this.files.writeJson(this.environment.files.active, active);
    this.writeNativeConfig(harness, profile.baseUrl, profile.apiKey, profile.model);
    this.writeEnv(active);
    return this.environment.files.env;
  }

  private read(): ActiveStore {
    return this.files.readJson<ActiveStore>(this.environment.files.active, {});
  }

  private writeEnv(active: ActiveStore): void {
    const lines = [
      '# Generated by harness-switch. Source this file in the shell where you launch your harness.',
      '# This file contains secrets. Do not commit it.',
    ];
    for (const [harness, profile] of Object.entries(active)) {
      if (!this.harnesses.has(harness)) {
        continue;
      }
      lines.push(`# ${this.harnesses.label(harness)} / ${profile.name}`);
      const values = {
        baseUrl: profile.base_url,
        apiKey: profile.api_key,
        model: profile.model,
      };
      for (const [env, field] of Object.entries(ENV_MAP[harness])) {
        if (values[field]) {
          lines.push(`export ${env}=${shellQuote(values[field])}`);
        }
      }
    }
    this.files.writeSecure(this.environment.files.env, `${lines.join('\n')}\n`);
  }

  private writeNativeConfig(
    harness: HarnessId,
    baseUrl: string,
    apiKey: string,
    model: string,
  ): void {
    const home = this.environment.homeDir;
    if (harness === 'claude') {
      const target = join(home, '.claude', 'settings.json');
      this.files.ensureDir(join(home, '.claude'));
      const current = this.files.readJson<Record<string, unknown>>(target, {});
      const env = {
        ...(current.env as Record<string, string> | undefined),
        ANTHROPIC_BASE_URL: baseUrl,
        ANTHROPIC_API_KEY: apiKey,
      };
      if (model) {
        env.ANTHROPIC_MODEL = model;
      }
      current.env = env;
      this.files.writeSecure(target, `${JSON.stringify(current, null, 2)}\n`);
    }
    if (harness === 'kimi') {
      const target = join(home, '.kimi', 'config.toml');
      const selected = model || 'kimi-for-coding';
      this.files.ensureDir(join(home, '.kimi'));
      const content = `default_model = "${escapeToml(selected)}"\n\n[providers.harness_switch]\ntype = "kimi"\nbase_url = "${escapeToml(baseUrl)}"\napi_key = "${escapeToml(apiKey)}"\n\n[models.harness_switch_model]\nprovider = "harness_switch"\nmodel = "${escapeToml(selected)}"\nmax_context_size = 262144\n`;
      this.files.writeSecure(target, content);
    }
  }
}

function shellQuote(value: string): string {
  return `'${String(value || '').replace(/'/g, `'"'"'`)}'`;
}

function escapeToml(value: string): string {
  return String(value || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"');
}
